### ISSUE TITLE
Remove Infinite Scroll

### ISSUE THREAD

**Issue by DZhang2** [makaroni4/focused_youtube#14]
Potential feature: Eliminate infinite scroll on the results page. Not sure if everyone would want this feature enabled, and in that case, a toggle button similar to the one for removing comments could be added, but I'm leaning towards simply having it enabled.

`body.fy-results-page ytd-continuation-item-renderer` (adding this line to the css prevents further video loading after the initial load. This usually results in around 15-20 videos loaded)

**Comment by HKanwal** [comment]
+1. Infinite scroll is a textbook addictive habit loop.

**Comment by makaroni4** [comment]
Hey gang 👋 

Awesome suggestion, although I think by default it's quite strict – I sometimes find my relevant videos in that section. I made it a toggle:

![Screenshot 2024-01-25 at 13 21 14](https://github.com/makaroni4/focused_youtube/assets/768070/d8dbebe8-d738-4c89-92c0-fa52f3d687d2)

Here's the commit that implements that feature: https://github.com/makaroni4/focused_youtube/commit/95d0f10c9ce12bde135a634b5e195393dbe4c720

Will be out in the next couple of days 🍻
