### ISSUE TITLE
Inject to mobile youtube too

### ISSUE THREAD

**Issue by alzifoztran** [makaroni4/focused_youtube#20]
I use kiwi browser and when i use this extension it didn't work maybe because it didn't inject the script for mobile youtube url `https://m.youtube.com`.

**Comment by makaroni4** [comment]
Hi @alzifoztran ☀️ 

I'm not sure how to make this extension available for the Kiwi browser, it works only in Chrome atm. 

It's open-source, if you want to give it a try and publish it under your name – it'll be my pleasure 🙌
