### ISSUE TITLE
Adblock support

### ISSUE THREAD

**Issue by chgpalmer** [makaroni4/focused_youtube#24]
Using Adblock plus with this extension seems to no longer work - I'm not sure how difficult this is to solve

(also thanks! this is a great addon)

**Comment by makaroni4** [comment]
@chgpalmer I hope it's OK if I close this one – looks like the extension works with both AdBlocks. Let's re-open the issue and dive deeper if it's still not working for you 🍻

**Comment by chgpalmer** [comment]
That's okay I haven't given more details so you cannot reproduce - I do still have a problem, I get an advert when looking at any youtube video, but as soon as I refresh the page it does successfully skip the advert

**Comment by makaroni4** [comment]
Interesting! I wonder if it's an Adblock issue on your account (maybe due to some YouTube AB-test that's specific to your account). 🤞
