### ISSUE TITLE
image on home screen

### ISSUE THREAD

**Issue by Emanuel3queijos** [makaroni4/focused_youtube#26]
Hi, I was thinking about putting the option to add image on the home screen, what do you think?

**Comment by makaroni4** [comment]
Hey @mano3queijos 👋 

Interesting, what kind of image do you have in mind? 

💡 The minimalism of the current homepage (just a search bar) is done on purpose to keep one focused only on one thing – input a search query.

**Comment by makaroni4** [comment]
Hi @Emanuel3queijos 👋 

Let's keep FY minimalistic? 🙏 

I'll close this one if you don't mind.
