### ISSUE TITLE
Add Option to Remove Video Descriptions

### ISSUE THREAD

**Issue by Yashh0** [makaroni4/focused_youtube#28]
Suggesting the addition of a feature that allows users to remove video descriptions while using the extension.
This would help minimize distractions and keep the focus solely on the video content.

**Comment by makaroni4** [comment]
Hey @Yashh0 👋 

Great idea, thank you 🙌  I've added the option:

![Screenshot 2024-09-01 at 14 16 01](https://github.com/user-attachments/assets/19fc4cd1-918a-47a1-ab1a-ed24294de5c3)

I'll publish it soon once we finish the enabled/disabled option PR: https://github.com/makaroni4/focused_youtube/pull/33

**Comment by Yashh0** [comment]
wow i thought this repo is dead
