### ISSUE TITLE
Youtube changed its layout

### ISSUE THREAD

**Issue by cfishyyyyy** [makaroni4/focused_youtube#29]
it seems youtube is testing a new layout for some users, where the recommended videos appear below on the left, and the video description and comments appear on the right. The extension no longer hides the recommended videos below. The extension worked amazingly before and was a life saver for me, could you please update it to function with youtube's new layout? thank you

**Comment by makaroni4** [comment]
Hey @cfishyyyyy 👋 

Oh snap, sneaky YouTube folks! 💣 Could you please take a screenshot with the new layout? Maybe you can share a YouTube URL where you see it? (maybe it's video-based?)

**Comment by Mexikon** [comment]
![Uploading Bildschirmfoto 2024-04-19 um 18.05.17.png…]()

**Comment by Mexikon** [comment]
[Bildschirmfoto 2024-04-19 um 18.05.17.pdf](https://github.com/makaroni4/focused_youtube/files/15042933/Bildschirmfoto.2024-04-19.um.18.05.17.pdf)

**Comment by makaroni4** [comment]
Wow, the new layout looks ... not good 😬 I'm still running on the old one (also found the video from the snapshot – I'm still setting the old layout).

@Mexikon could you please locate the new block identifier, so we can hide it? 

We need a section tag and ideally a unique id (class name):

![Screenshot 2024-04-23 at 21 34 32](https://github.com/makaroni4/focused_youtube/assets/768070/6131515a-e68b-4d1e-9fb1-73f7df9d0438)

Here's the line of code that removes the section: https://github.com/makaroni4/focused_youtube/blob/main/src/style-overrides.css#L130

If you open a dev console and inspect this new section I'm happy to add the selector to the list of blocked sections. 🔧

**Comment by makaroni4** [comment]
Can't get a hand on the new layout, maybe it was an AB-test in the end?

Anyways, I'll close this one for now. Ping me if you can get a new layout markup 🙏
