### ISSUE TITLE
View History / other features from side bar option

### ISSUE THREAD

**Issue by phaneendra2429** [makaroni4/focused_youtube#30]
Please add an option to visit Video history. Unable to find the videos easily after viewing in my mobile phone.

**Comment by makaroni4** [comment]
@phaneendra2429 awesome idea, I've added a menu – you need to hover over the YouTube logo to see it:

![Screenshot 2024-08-30 at 15 23 06](https://github.com/user-attachments/assets/6531158f-7884-4f9b-84ea-9c9feb6faa76)

https://github.com/makaroni4/focused_youtube/pull/36

I'll publish the new extension version in the next couple of days.

Thank you 🍻
