### ISSUE TITLE
add option to turn it off or on with a in the menu

### ISSUE THREAD

**Issue by KParthSingh** [makaroni4/focused_youtube#31]
Add option to turn off and on the extension like in the below image.
![Screenshot 2024-08-25 195044](https://github.com/user-attachments/assets/8dd6d978-28c5-4d2e-b8f9-ce2c82afd6cf)
This is the only thing that is stopping me to switch to this extension.

So far everything is great about this extension.

**Comment by KParthSingh** [comment]
Hey @fauzanabrar can you help with this? looks like is @makaroni4 is inactive.

**Comment by makaroni4** [comment]
Thank you for pushing this one @KParthSingh, this is happening 🚀 

https://github.com/makaroni4/focused_youtube/pull/33
