### ISSUE TITLE
[Bug] Theatre mode isn't working properly.

### ISSUE THREAD

**Issue by KParthSingh** [makaroni4/focused_youtube#38]
Found this video bug when i was watching [this video](https://www.youtube.com/watch?v=EMPjgL2LNSU&list=PL2xF3HCNxGM-u96iJBHtwY733QgthoGu-&index=7).
In theatre mode video doesn't stretches to full screen. _(pardon me for my poor choice of words)_
![Screenshot 2024-09-06 221347](https://github.com/user-attachments/assets/31aaaeeb-ac49-4086-94c4-d3e1ac2ef545)
After inspecting the page i found deleting this line of code fixes this weird behaviour
`<div id="panels-full-bleed-container" class="style-scope ytd-watch-flexy"></div>`

Edit: this has something to do with live chat panels because this is only happening in live videos or the videos that were posted as live.

**Comment by makaroni4** [comment]
Great catch @KParthSingh, thank you 🙌 

Fixed, just published a new release. ✅

**Comment by KParthSingh** [comment]
Thanks man!
