### ISSUE TITLE
Comments are not loading when enabled

### ISSUE THREAD

**Issue by popema06** [makaroni4/focused_youtube#39]
Sometimes (not always, which is odd) comments are not showing up (even when enabled in the panel addon setting). When switching from enabled/disabled back to back, it's not helping (in the previous version comments started to load, when I did quick off/on).

(Google Chrome, version 128.0.6613.120)

**Comment by makaroni4** [comment]
Hey @popema06 👋 

Interesting, is it flakey on the same video, or maybe there're some videos where it works randomly? Could you please send a link to one where it's acting up? 🙏

**Comment by popema06** [comment]
I'd say it happens more sporadically than with the same videos. This has only happened once since I opened this issue and refreshing the page fixed it this time. I know this is an imperfect description, I was wondering if anyone else had experienced this. I'll try to find a pattern.

**Comment by makaroni4** [comment]
@popema06 I think I've found the problem – for a person who never tweaked the settings, they were acting as disabled. I just pushed the new extension version with a fix (1.17), I hope it'll be it 🤞

**Comment by makaroni4** [comment]
@popema06 I think I've found it – it was incorrect FY class name cleanup [here](https://github.com/makaroni4/focused_youtube/commit/b39ceaf84ec179fb74fee9009715b5fccd6976c6#diff-4c7ccfc5851fc8bba0def5206dca7b37725f7f3f84e598ed266f5448faf62965R48).

The results page class (`fy-results-page`) was still there on the video page and it was causing the wrapper of the comment section to be hidden. The randomness came from a race condition between DOM updates and URL change – I was trying to re-initialize the extension on the `popstate` event or on the Navigation change event, but both didn't work 💣 

I wonder if there's a nicer solution where we initialize the extension when both DOM changes and URL change has been completed. 🤔 

@popema06 I've added the latest dist folder back to the repo, could you please test the extension locally and tell me if it works? (worked 10/10 times for me) 🙏 https://github.com/makaroni4/focused_youtube?tab=readme-ov-file#development

**Comment by popema06** [comment]
@makaroni4 It works perfectly! There are now comments even under live videos that were previously hidden. Great job 👍

**Comment by makaroni4** [comment]
Weee hooo 🚀 So glad we found a bug, thank you very much @popema06 🙌 

I've published the `1.18` version with a fix, should be live within a couple of days 🚀
