### ISSUE TITLE
Not working on /live urls

### ISSUE THREAD

**Issue by wouternolten** [makaroni4/focused_youtube#40]
I was watching Youtube and noticed the plugin doesn't work on urls with /live in them.

For instance: https://www.youtube.com/live/KtHn59wqdBc
But, of course this one needs to be included as well: https://www.youtube.com/live/dQw4w9WgXcQ

Browser: Brave, v1.69.162 with chromium 128.0.6613.120

Feel free to ask if you need more info!

**Comment by makaroni4** [comment]
Hey @wouternolten 👋 

Great catch, thank you very much for the issue 🙌 

It's fixed, I just published a new release, should be live within the next couple of days. 🚀 

https://github.com/makaroni4/focused_youtube/commit/3cd07b003dea576c67358802e764412b30871d3a

**Comment by wouternolten** [comment]
Sick, that was fast. Awesome, thanks a ton!

**Comment by makaroni4** [comment]
Just got an email that the new version has been approved 💥 

The fastest release ever? 🏆
