### ISSUE TITLE
Updating Dependencies

### ISSUE THREAD

**Issue by thesolomon-tech** [makaroni4/focused_youtube#42]
Hi,

I noticed 7 vulnerabilities with the packages and they were out of date.
I created an updated version https://github.com/thesolomon-tech/focused_youtube_updated with a new config file for ESLint.

There were a lot of these errors during npm run build: 
"chrome-extension://__MSG_@@extension_id__/fonts/Roboto-Regular.ttf referenced in chrome-extension://__MSG_@@extension_id__/fonts/Roboto-Regular.ttf didn't resolve at build time, it will remain unchanged to be resolved at runtime" but they did not seem to impact the product, which appeared to work fine.

**Comment by makaroni4** [comment]
Hola @thesolomon-tech 👋 

That's awesome, thank you so much! Could you please open a PR? Let's merge it in 🚀

**Comment by thesolomon-tech** [comment]
Great! I made #43

**Comment by makaroni4** [comment]
Merged, you're 🚀 @thesolomon-tech 🙌
