### ISSUE TITLE
Options to see account handle in top right corner?

### ISSUE THREAD

**Issue by MaxLenormand** [makaroni4/focused_youtube#46]
I've been using this extension over the past few weeks and loving it, thanks for making this!

1 feature request: Option to be able to see the account in the top right corner:
![CleanShot 2024-11-11 at 08 36 00@2x](https://github.com/user-attachments/assets/71b1233b-900d-4f01-a0ac-c798fa7a6d81)

Some reasons for this:
- Easy to change light / dark mode
- Easy to access YT settings
- (most important for me) know which account I'm on. I have multiple YT accounts for different channels and you like to quickly at a glance see which account I'm on

Cheers

**Comment by makaroni4** [comment]
Hey @MaxLenormand 👋 

Absolutely, great idea!

Do you think we should just show the profile picture or show a handle like `@makaroni4`? I think we can pull the profile name from the account link:

```js
const $usernameLink = document.querySelector('a[href^="/@"]');

if ($usernameLink) {
  const username = $usernameLink.href.replace("https://www.youtube.com/", "");
  console.log(username);

  // @makaroni4
}
```

**Comment by MaxLenormand** [comment]
I don't mind too much to see the handle name, as I already know what my handle is. I care more about being able to access my profile / see any notifications I may have (as I'm someone who also does post)

**Comment by makaroni4** [comment]
Sweet, then let's go with the avatar:

![Screenshot 2024-12-06 at 20 03 33](https://github.com/user-attachments/assets/6d472729-e7bc-4c7e-9c1e-b1cf3e3bb3b9)

I've made a new version, will publish after the current release goes live. 🚀

**Comment by MaxLenormand** [comment]
Appreciate the quick turn around, thank you! :)

**Comment by makaroni4** [comment]
Published, should be live in a couple of days ✅

**Comment by makaroni4** [comment]
It's live 💥
