### ISSUE TITLE
Add Dependabot

### ISSUE THREAD

**Issue by thesolomon-tech** [makaroni4/focused_youtube#47]
Hi,
Would it be possible to add Dependabot or some sort of automated checker to ensure dependencies are updated?
A good resource seems to be https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide#enabling-dependabot-for-your-repository

**Comment by makaroni4** [comment]
Hi @thesolomon-tech 👋 

Thank you for the suggestion. 🙌  I've enabled all Dependabot features. FY now has weekly Dependabot security alerts, version updates, etc  ✅
