### ISSUE TITLE
Darkmode on search page 

### ISSUE THREAD

**Issue by Kubot11** [makaroni4/focused_youtube#5]
Hi, your extension is almost ideal but the search page blinds me when I want to search a video. Can you add the dark mode?
![image](https://user-images.githubusercontent.com/99250816/202892826-decdf54e-0103-4519-8ca8-f7a311bee764.png)

**Comment by makaroni4** [comment]
Hi @Kubot11 👋 

It's been almost a week, I still see "Pending review" in Chrome Store 😞 

I'll ping you when it goes live ⏰

**Comment by makaroni4** [comment]
It's live, thank you very much @Kubot11 🍻
