### ISSUE TITLE
Resize bug 

### ISSUE THREAD

**Issue by Kubot11** [makaroni4/focused_youtube#6]
When resizing page to 150% the menu appears on left side:
![image](https://user-images.githubusercontent.com/99250816/202899491-c39e103b-e883-46b0-b386-492834c07764.png)

**Comment by makaroni4** [comment]
@Kubot11 this has been released as well, right?

**Comment by makaroni4** [comment]
Ahh, it's the `. ytd-mini-guide-renderer`. @Kubot11 I just submitted another version for review that fixes it 🤞

**Comment by makaroni4** [comment]
It's live and I see it's fixed, thank you @Kubot11  🍻
